### ISSUE TITLE
Roassal 2 is deprecated

### ISSUE THREAD

**Issue by jordanmontt** [pharo-ai/viz#7]

**Comment by hernanmd** [comment]
Hi Jordan.
Is Roassal 2 deprecated also for Pharo 8?

The Roassal 2 classes only loads in Pharo 8 where it is working.

**Comment by jordanmontt** [comment]
Hello Hernan,

I don't know about Pharo 8. Do you think that we should keep maintaining the project for Pharo 8?

In my opinion, we should only focus on Pharo 9 and 10.

Thanks

**Comment by hernanmd** [comment]
I think nobody is using AI packages in Pharo 8.
So this could be closed and #9 should be done
